[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "Ctd8BHaHPD7QUjk18SeRkaadpkR5dDF2opq4Cn6vGPii"
agent_registry = "D6ixuieTocq25Rf2Ru4qAAuxSPx5mbR6UABjY7PoNDnh"
settlement = "DQj9jfTNEaMCrUD8DfAiRkcmMiragBYv33Qh27ZiZuYU"
audit_log = "9kDA9TbKmTMdSEpM4ZpYTYAmniuETRVL3uWWrS6CQ7ZG"

[programs.devnet]
vault = "Ctd8BHaHPD7QUjk18SeRkaadpkR5dDF2opq4Cn6vGPii"
agent_registry = "D6ixuieTocq25Rf2Ru4qAAuxSPx5mbR6UABjY7PoNDnh"
settlement = "DQj9jfTNEaMCrUD8DfAiRkcmMiragBYv33Qh27ZiZuYU"
audit_log = "9kDA9TbKmTMdSEpM4ZpYTYAmniuETRVL3uWWrS6CQ7ZG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tests/tsconfig.json -t 60000 ./tests/**/*.test.ts"
